apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-bff-web-store
  namespace: local-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-bff-web-store
  template:
    metadata:
      labels:
        app: demo-bff-web-store
    spec:
      containers:
        - name: demo-bff-web-store-container
          image: demo-bff-web-store:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "300m" 
              memory: "256Mi" 
            requests:
              cpu: "150m" 
              memory: "128Mi"   
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/store-books-bff"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://demo-store-db:5433/store"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dbusername"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dbpassword"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-bff-web-store
  namespace: local-cicd
spec:
  selector:
    app: demo-bff-web-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 