apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-bff-web-marketing
  namespace: local-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-bff-web-marketing
  template:
    metadata:
      labels:
        app: demo-bff-web-marketing
    spec:
      containers:
        - name: demo-bff-web-marketing-container
          image: demo-bff-web-marketing:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "300m" 
              memory: "256Mi" 
            requests:
              cpu: "150m" 
              memory: "128Mi"   
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/marketing-blogs-bff"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://demo-marketing-db:5432/marketing"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dbusername"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dbpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-bff-web-marketing
  namespace: local-cicd
spec:
  selector:
    app: demo-bff-web-marketing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 